"""Add SLA notification flag to Issue

Revision ID: 5bb9ee37f5f6
Revises: 6bb3fa7f5872
Create Date: 2026-07-15 08:53:27.635184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb9ee37f5f6'
down_revision = '6bb3fa7f5872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_notification_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('sla_notification_sent')

    # ### end Alembic commands ###
