"""Add location and embedding to issues

Revision ID: 6bb3fa7f5872
Revises: dceed5062145
Create Date: 2026-07-14 08:13:55.782350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb3fa7f5872'
down_revision = 'dceed5062145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suggested_department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('embedding', sa.JSON(), nullable=False))
        batch_op.create_index(batch_op.f('ix_issues_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_longitude'), ['longitude'], unique=False)
        batch_op.create_foreign_key(None, 'departments', ['suggested_department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_issues_longitude'))
        batch_op.drop_index(batch_op.f('ix_issues_latitude'))
        batch_op.drop_column('embedding')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('suggested_department_id')

    # ### end Alembic commands ###
